name: 'Check for merge conflicts'
on:
  push:
    branches:
      - master
jobs:
  triage:
    runs-on: ubuntu-20.04
    steps:
      - uses: mschilde/auto-label-merge-conflicts@5981f8933e92b78098af86b9e33fe0871cc7a3be
        with:
          CONFLICT_LABEL_NAME: 'Merge Conflict'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WAIT_MS: 10000
